//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLayerLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Fields are Present.
        /// </summary>
        internal static string AllFieldsPresent {
            get {
                return ResourceManager.GetString("AllFieldsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Id is Missing.
        /// </summary>
        internal static string DepartmentIDMissing {
            get {
                return ResourceManager.GetString("DepartmentIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation is Missing.
        /// </summary>
        internal static string DesignationMissing {
            get {
                return ResourceManager.GetString("DesignationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id Found.
        /// </summary>
        internal static string EmployeeIdFound {
            get {
                return ResourceManager.GetString("EmployeeIdFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id is Missing.
        /// </summary>
        internal static string EmployeeIdMissing {
            get {
                return ResourceManager.GetString("EmployeeIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name is Missing.
        /// </summary>
        internal static string EmployeeNameMissing {
            get {
                return ResourceManager.GetString("EmployeeNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee working on Maximum number of Projects.
        /// </summary>
        internal static string MaxProjectsByEmployee {
            get {
                return ResourceManager.GetString("MaxProjectsByEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Projects Managed by Employee.
        /// </summary>
        internal static string MaxProjectsManagedByEmployee {
            get {
                return ResourceManager.GetString("MaxProjectsManagedByEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Number of Technology already assigned to Task.
        /// </summary>
        internal static string MaxTechnologyAssigned {
            get {
                return ResourceManager.GetString("MaxTechnologyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete Active Project.
        /// </summary>
        internal static string ProjectActive {
            get {
                return ResourceManager.GetString("ProjectActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task cannot be assigned to completed Project.
        /// </summary>
        internal static string ProjectCompleted {
            get {
                return ResourceManager.GetString("ProjectCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Count exceeded for deleting technology.
        /// </summary>
        internal static string ProjectCountExceeded {
            get {
                return ResourceManager.GetString("ProjectCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id Found.
        /// </summary>
        internal static string ProjectIdFound {
            get {
                return ResourceManager.GetString("ProjectIdFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id is Missing.
        /// </summary>
        internal static string ProjectIdMissing {
            get {
                return ResourceManager.GetString("ProjectIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name Already Exists.
        /// </summary>
        internal static string ProjectNameExists {
            get {
                return ResourceManager.GetString("ProjectNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name is Missing.
        /// </summary>
        internal static string ProjectNameMissing {
            get {
                return ResourceManager.GetString("ProjectNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Id is Missing.
        /// </summary>
        internal static string RoleIDMissing {
            get {
                return ResourceManager.GetString("RoleIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusId is Missing.
        /// </summary>
        internal static string StatusIdMissing {
            get {
                return ResourceManager.GetString("StatusIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete Active Task.
        /// </summary>
        internal static string TaskActive {
            get {
                return ResourceManager.GetString("TaskActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id Found.
        /// </summary>
        internal static string TaskIdFound {
            get {
                return ResourceManager.GetString("TaskIdFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskId is Missing.
        /// </summary>
        internal static string TaskIdMissing {
            get {
                return ResourceManager.GetString("TaskIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Id Found.
        /// </summary>
        internal static string TechnologyIdFound {
            get {
                return ResourceManager.GetString("TechnologyIdFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Id is Missing.
        /// </summary>
        internal static string TechnologyIdMissing {
            get {
                return ResourceManager.GetString("TechnologyIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology not assigned in Project.
        /// </summary>
        internal static string TechnologyMissingInProject {
            get {
                return ResourceManager.GetString("TechnologyMissingInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Name already Exists.
        /// </summary>
        internal static string TechnologyNameExists {
            get {
                return ResourceManager.GetString("TechnologyNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Name is Missing.
        /// </summary>
        internal static string TechnologyNameMissing {
            get {
                return ResourceManager.GetString("TechnologyNameMissing", resourceCulture);
            }
        }
    }
}
